import "../../styles/globals.css";
import { Inter, Pixelify_Sans as Pixel } from "next/font/google";
import Navbar from "~/components/Navbar";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
import Providers from "~/components/Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const pixel = Pixel({
  subsets: ["latin"],
  variable: "--font-pixel",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`relative min-h-screen bg-black font-sans  ${inter.variable} ${pixel.variable}`}
      >
        <Providers>
          <Navbar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
