import "~/styles/globals.css";

import { Inter, Pixelify_Sans as Pixel } from "next/font/google";
import Navbar from "~/components/Navbar";
import { Suspense } from "react";
import SearchPokemon from "~/components/SearchPokemon";
import { SearchPokemonFallback } from "~/components/Index/PokemonGrid";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const pixel = Pixel({
  subsets: ["latin"],
  variable: "--font-pixel",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="pokemon-bg container  flex h-full flex-wrap   justify-center gap-12  py-12   ">
      <Suspense fallback={<SearchPokemonFallback />}>
        <SearchPokemon />
      </Suspense>

      {children}
    </main>
  );
}
